# Generated by Django 6.0.2 on 2026-02-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('technical', 'Technical'), ('hr', 'HR')], default='coding', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('technical', 'Technical'), ('hr', 'HR')], default='coding', max_length=20),
        ),
    ]
