# Generated by Django 6.0.2 on 2026-02-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_question_question_type_topic_topic_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_type',
        ),
    ]
